CREATE TABLE publikacje(
    id NUMBER(5) PRIMARY KEY,
    tytul VARCHAR2(255) ,
    rok NUMBER(4),
    autorzy NUMBER(3),
    punkty NUMBER(5)
);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (1, 'Function definitions for compound values in object-oriented languages', 2017, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (2, 'Regular Separability of Parikh Automata', 2017, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (3, 'Separability of Reachability Sets of Vector Addition Systems', 2017, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (4, 'Timed pushdown automata and branching vector addition systems', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (5, 'Regular separability of one counter automata', 2017, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (6, 'Rule-Based Reasoning with Belief Structures', 2017, 3, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (7, 'Heterogeneous Approximate Reasoning with Graded Truth Values', 2017, 4, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (8, 'The Spectrum of Equilibria for the Colonel Blotto and the Colonel Lotto Games', 2017, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (9, 'Detecting Locus Acquisition Events in Gene Trees', 2017, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (10, 'New Algorithms for the Genomic Duplication Problem', 2017, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (11, 'Bounding Average-Energy Games', 2017, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (12, 'On BĂĽchi One-Counter Automata', 2017, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (13, 'Linear combinations of unordered data vectors', 2017, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (14, 'SMIS 2017 Data Mining Competition: Trading Based on Recommendations', 2017, 7, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (15, 'Decremental Single-source Reachability in Planar Digraphs', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (16, 'Contracting a Planar Graph Efficiently', 2017, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (17, 'Modal mu-Calculus with Atoms', 2017, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (18, 'Expressiveness of Probabilistic Modal Logics, Revisited', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (19, 'Learning nominal automata', 2017, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (20, 'Efficient Enumeration of Non-Equivalent Squares in Partial Words with Few Holes', 2017, 8, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (21, 'LOIS: Syntax and Semantics', 2017, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (22, 'On the Computational Complexity of Gossip Protocols', 2017, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (23, 'Programming Languages in GitHub: A Visualization in Hyperbolic Plane', 2017, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (24, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (25, 'Approximation and Parameterized Complexity of Minimax Approval Voting', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (26, 'Tight Lower Bounds for the Complexity of Multicoloring', 2017, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (27, 'A Fast Deterministic Detection of Small Pattern Graphs in Graphs Without Large Cliques', 2017, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (28, 'Axiomatic Characterization of Game-Theoretic Network Centralities', 2017, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (29, 'The Dollar Auction with Spiteful Players', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (30, 'On the Construction of Covert Networks', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (31, 'Strategic Social Network Analysis', 2017, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (32, 'Dynamic Beats Fixed: On Phase-Based Algorithms for File Migration', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (33, 'On Problems Equivalent to (min, +)-Convolution', 2017, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (34, 'Bisimilarity for paraconsistent description logics', 2017, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (35, 'Why Do Cascade Sizes Follow a Power-Law?', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (36, 'Approximation and Kernelization for Chordal Vertex Deletion', 2017, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (37, 'Edge Bipartization Faster Than 2^k', 2017, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (38, 'Subexponential Parameterized Algorithms for Graphs of Polynomial Growth', 2017, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (39, 'Exploring the Complexity of Layout Parameters in Tournaments and Semi-Complete Digraphs', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (40, 'Model-checking for successor-invariant first-order formulas on graph classes of bounded expansion', 2017, 6, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (41, 'Optimizing Tree Decompositions in MSO', 2017, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (42, 'Linear Kernels for Edge Deletion Problems to Immersion-Closed Graph Classes', 2017, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (43, 'Fully polynomial-time parameterized computations for graphs and matrices of low treewidth', 2017, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (44, 'Cutwidth: Obstructions and Algorithmic Aspects', 2017, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (45, 'Neighborhood Complexity and Kernelization for Nowhere Dense Classes of Graphs', 2017, 7, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (46, 'Approximation and Parameterized Algorithms for Geometric Independent Set with Shrinking', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (47, 'On Low Rank-Width Colorings', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (48, 'Streaming K-Mismatch with Error Correcting and Applications', 2017, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (49, 'Palindromic Decompositions with Gaps and Errors', 2017, 5, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (50, 'Longest Common Factor After One Edit Operation', 2017, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (51, 'Faster Algorithms for 1-Mappability of a Sequence', 2017, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (52, 'Optimizing egalitarian performance in the side-effects model of colocation for data center resource management', 2017, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (53, 'Negative-Weight Shortest Paths and Unit Capacity Minimum Cost Flow in Ă•(m^10/7 log W) Time', 2017, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (54, 'Improved Distance Queries and Cycle Counting by Frobenius Normal Form', 2017, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (55, 'Approximate Nearest Neighbors Search Without False Negatives For l_2 For c>sqrtloglogn', 2017, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (56, 'Automata Theory Approach to Predicate Intuitionistic Logic', 2017, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (57, 'Attachment Centrality for Weighted Graphs', 2017, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (58, 'Connecting Decidability and Complexity for MSO Logic', 2017, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (59, 'A Characterisation of Pi^0_2 Regular Tree Languages', 2017, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (60, 'Scalable Machine Learning with Granulated Data Summaries: A Case of Feature Selection', 2017, 3, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (61, 'When the Optimum is also Blind: a New Perspective on Universal Optimization', 2017, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (62, 'Binary Reachability of Timed Pushdown Automata via Quantifier Elimination and Cyclic Order Atoms', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (63, 'Online Facility Location with Deletions', 2018, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (64, 'Universal Trees Grow Inside Separating Automata: Quasi-Polynomial Lower Bounds for Parity Games', 2018, 6, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (65, 'Unboundedness Problems for Languages of Vector Addition Systems', 2018, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (66, 'Regular Separability of Well-Structured Transition Systems', 2018, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (67, 'FairSwap: How To Fairly Exchange Digital Goods', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (68, 'General State Channel Networks', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (69, 'Individual Security and Network Design with Malicious Nodes', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (70, 'The Wasserstein Distance as a Dissimilarity Measure for Mass Spectra with Application to Spectral Deconvolution', 2018, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (71, 'Cophenetic Distances: A Near-Linear Time Algorithmic Framework', 2018, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (72, 'Linear Equations with Ordered Data', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (73, 'The IPv6 Routing Protocol for Low-power and Lossy Networks (RPL) under Network Partitions', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (74, 'Ad Hoc 802.11-802.15.4 Crosstalk-Based Communication in Practice', 2018, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (75, 'On Designing Provably Correct DODAG Formation Criteria for the IPv6 Routing Protocol for Low-Power and Lossy Networks (RPL)', 2018, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (76, 'A Distributed Systems Perspective on Industrial IoT', 2018, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (77, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches', 2018, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (78, 'Improving Hearthstone AI by Combining MCTS and Supervised Learning Algorithms', 2018, 3, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (79, 'Decremental Transitive Closure and Shortest Paths for Planar Digraphs and Beyond', 2018, 1, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (80, 'Optimal Dynamic Strings', 2018, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (81, 'Improved Bounds for Shortest Paths in Dense Distance Graphs', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (82, 'Decremental SPQR-trees for Planar Graphs', 2018, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (83, 'On Periodicity Lemma for Partial Words', 2018, 4, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (84, 'Faster Recovery of Approximate Periods over Edit Distance', 2018, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (85, 'Linear-Time Algorithm for Long LCF with k Mismatches', 2018, 8, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (86, 'String Periods in the Order-Preserving Model', 2018, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (87, 'Efficient Computation of Sequence Mappability', 2018, 7, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (88, 'On Directed Feedback Vertex Set Parameterized by Treewidth', 2018, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (89, 'WQO Dichotomy for 3-Graphs', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (90, 'Quantifying Algorithmic Improvements over Time', 2018, 6, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (91, 'Finite Query Answering in Expressive Description Logics with Transitive Roles', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (92, 'On Fuzzy Sheffer Stroke Operation', 2018, 6, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (93, 'Recursion Schemes and the WMSO+U Logic', 2018, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (94, 'The Complexity of the Diagonal Problem for Recursion Schemes', 2018, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (95, 'An Improved FPT Algorithm for Independent Feedback Vertex Set', 2018, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (96, 'On Subexponential Parameterized Algorithms for Steiner Tree and Directed Subset TSP on Planar Graphs', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (97, 'Experimental Evaluation of Parameterized Algorithms for Feedback Vertex Set', 2018, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (98, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation', 2018, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (99, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-Wideness', 2018, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (100, 'First-Order Interpretations of Bounded Expansion Classes', 2018, 7, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (101, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs', 2018, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (102, 'Parameterized circuit complexity of model-checking on sparse structures', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (103, 'Definable decompositions for graphs of bounded linear cliquewidth', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (104, 'On the number of types in sparse graphs', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (105, 'Broadcast with Energy-Exchanging Mobile Agents Distributed on a Tree', 2018, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (106, 'Dfuntest: A Testing Framework for Distributed Applications', 2018, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (107, 'Collective Schedules: Scheduling Meets Computational Social Choice', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (108, 'Reducing Transducer Equivalence to Register Automata Problems Solved by "Hilbert Method', 2018, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (109, 'Approval-Based Multi-Winner Rules and Strategic Voting', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (110, 'Consistent Approval-Based Multi-Winner Rules', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (111, 'Stable Marriage with Multi-Modal Preferences', 2018, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (112, 'Multiwinner Elections With Diversity Constraints', 2018, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (113, 'On the Complexity of Extended and Proportional Justified Representation', 2018, 6, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (114, 'Proportional Approval Voting, Harmonic k-median, and Negative Association', 2018, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (115, 'How Deterministic are Good-For-Games Automata?', 2018, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (116, 'Unambiguous Languages Exhaust the Index Hierarchy', 2018, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (117, 'Investigating Similarity between Hearthstone Cards: Text Embeddings and Interchangeability Approaches', 2018, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (118, 'Ranking mutual information dependencies in a summary-based approximate analytics framework', 2018, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (119, 'On computability and tractability for infinite sets', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (120, 'An Axiomatization of the Eigenvector and Katz Centralities', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (121, 'Axiomatization of the PageRank Centrality', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (122, 'Random Order Contention Resolution Schemes', 2018, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (123, 'Multi3Net: Segmenting Flooded Buildings via Fusion of Multiresolution, Multisensor, and Multitemporal Satellite Imagery', 2019, 7, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (124, 'String-to-String Interpretations With Polynomial-Size Output', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (125, 'A non-regular language of infinite trees that is recognizable by a sort-wise finite algebra', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (126, 'Regular tree languages in low levels of the Wadge Hierarchy', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (127, 'MSO+nabla is undecidable', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (128, 'Occupational injury risk wage premium', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (129, 'Timed Basic Parallel Processes', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (130, 'Efficient reduction of nondeterministic automata with application to language inclusion testing', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (131, 'Binary Reachability of Timed-register Pushdown Automata and Branching Vector Addition Systems', 2019, 4, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (132, 'On Problems Equivalent to (min, +)-Convolution', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (133, 'Improving TSP Tours Using Dynamic Programming over Tree Decompositions', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (134, 'Minimum Bisection Is Fixed-Parameter Tractable', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (135, 'Applying deep learning to right whale photo identification', 2019, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (136, 'Shortest paths in one-counter systems', 2019, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (137, 'Regular Separability of One Counter Automata', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (138, 'The Reachability Problem for Petri Nets is Not Elementary', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (139, 'New Pumping Technique for 2-Dimensional VASS', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (140, 'Improved Bounds for the Excluded-Minor Approximation of Treedepth', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (141, 'Energy-optimal broadcast and exploration in a tree using mobile agents', 2019, 4, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (142, 'qDSB-Seq is a general method for genome-wide quantification of DNA double-strand breaks using sequencing', 2019, 12, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (143, 'A paraconsistent approach to actions in informationally complex environments', 2019, 3, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (144, 'Belief Shadowing', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (145, 'Doxastic Group Reasoning via Multiple Belief Shadowing', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (146, 'BDI Model of Connected and Autonomous Vehicles', 2019, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (147, 'Simple Refreshing in the Noisy Leakage Model', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (148, 'Unifying Leakage Models: From Probing Attacks to Noisy Leakage', 2019, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (149, 'Perun: Virtual Payment Hubs over Cryptocurrencies', 2019, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (150, 'Multi-party Virtual State Channels', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (151, 'Progressive Algorithms for Domination and Independence', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (152, 'Jaccard/Tanimoto similarity test and estimation methods for biological presence-absence data', 2019, 4, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (153, 'Automatic mapping of atoms across both simple and complex chemical reactions', 2019, 9, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (154, 'Biologically sound formal model of Hsp70 heat induction', 2019, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (155, 'MIND: A double-linear model to accurately determine monoisotopic precursor mass in high-resolution top-down proteomics', 2019, 10, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (156, 'Truncated Robust Principal Component Analysis and Noise Reduction for Single Cell RNA Sequencing Data', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (157, 'masstodon: A tool for assigning peaks and modeling electron transfer reactions in top-down mass spectrometry', 2019, 7, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (158, 'Mapping of breakpoints in balanced chromosomal translocations by shallow whole genome sequencing points to EFNA5, BAHD1 and PPP2R5E as novel candidates for genes causing human Mendelian disorders', 2019, 22, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (159, 'Credibility of Evolutionary Events in Gene Trees', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (160, 'Mathematical properties of the gene duplication cost', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (161, 'Feasibility Algorithms for the Duplication-Loss Cost', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (162, 'High-Throughput BCR Sequencing and Single-Cell Transcriptomics Reveal Distinct Transcriptional Profiles Associated with Subclonal Evolution of Follicular Lymphoma', 2019, 13, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (163, 'Continuous Reachability for Unordered Data Petri Nets is in PTime', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (164, '30 Sensors to Mars: Toward Distributed Support Systems for Astronauts in Space Habitats', 2019, 7, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (165, 'GRUNGE: A Grand Unified ATP Challenge', 2019, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (166, 'Declarative Proof Translation', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (167, 'Higher-Order Tarski Grothendieck as a Foundation for Formal Proof', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (168, 'Reliable Hubs for Partially-Dynamic All-Pairs Shortest Paths in Directed Graphs', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (169, 'Min-Cost Flow in Unit-Capacity Planar Graphs', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (170, 'Codensity Games for Bisimilarity', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (171, 'Scalar and Vectorial mu-calculus with Atoms', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (172, 'History-Dependent Nominal mu-Calculus', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (173, 'Expressiveness of probabilistic modal logics: A gradual approach', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (174, 'Definable isomorphism problem', 2019, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (175, 'Logical properties of random graphs from small addable classes', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (176, 'Fine-Grained Complexity of k-OPT in Bounded-Degree Graphs for Solving TSP', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (177, 'Tight Lower Bounds for the Complexity of Multicoloring', 2019, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (178, 'Rare Siblings Speed-Up Deterministic Detection and Counting of Small Pattern Graphs', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (179, 'A fast deterministic detection of small pattern graphs in graphs without large cliques', 2019, 2, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (180, 'Structure and function of the Ts2631 endolysin of Thermus scotoductus phage vB_Tsc2631 with unique N-terminal extension used for peptidoglycan binding', 2019, 7, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (181, 'Enumerating Connected Subgraphs and Computing the Myerson and Shapley Values in Graph-restricted Games', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (182, 'Attachment Centrality: Measure for Connectivity in Networks', 2019, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (183, 'Strategic Attack ' || CHR(38) || ' Defense in Security Diffusion Games', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (184, 'Attacking Similarity-Based Link Prediction in Social Networks', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (185, 'A Measure of Added Value in Groups', 2019, 5, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (186, 'How to Hide oneâ€™s Relationships from Link prediction Algorithms', 2019, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (187, 'Adversarial Robustness of Similarity-Based Link Prediction', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (188, 'A Subquadratic Approximation Scheme for Partition', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (189, 'Equal-subset-sum faster than the meet-in-the-middle', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (190, 'On the semantics of Cypher''s implicit group-by', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (191, 'On Finite and Unrestricted Query Entailment beyond SQ with Number Restrictions on Transitive Roles', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (192, 'Credibility of Evolutionary Events in Gene Trees', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (193, 'The Influence of the Test Operator on the Expressive Power of PDL-like Logics', 2019, 1, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (194, 'Bisimilarity in Fuzzy Description Logics Under the Zadeh Semantics', 2019, 1, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (195, 'Minimizing interpretations in fuzzy description logics under the GĂ¶del semantics by using fuzzy bisimulations', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (196, 'An expressive and tractable rule-based description language', 2019, 2, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (197, 'Bisimulations for Fuzzy Description Logics with Involutive Negation Under the GĂ¶del Semantics', 2019, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (198, 'Incorporating Stratified Negation into Query-Subquery Nets for Evaluating Queries to Stratified Deductive Databases', 2019, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (199, 'PyLink: a PyMOL plugin to identify links', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (200, 'Defining and detecting links in chromosomes', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (201, 'Parity Games: Zielonka''s Algorithm in Quasi-Polynomial Time', 2019, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (202, 'Extensions of the Caucal Hierarchy?', 2019, 1, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (203, 'Inferring duplication episodes from unrooted gene trees', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (204, 'Efficient algorithms for genomic duplication models', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (205, 'The Worst Balanced Partially Ordered Setsâ€”Ladders with Broken Rungs', 2019, 1, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (206, 'Finding Hamiltonian Cycle in Graphs of Bounded Treewidth: Experimental Evaluation', 2019, 2, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (207, 'Deleting Vertices to Graphs of Bounded Genus', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (208, 'An Exponential Lower Bound for Cut Sparsifiers in Planar Graphs', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (209, 'Polynomial-time algorithm for Maximum Weight Independent Set on P6-free graphs', 2019, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (210, 'Turing Kernelization for Finding Long Paths in Graph Classes Excluding a Topological Minor', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (211, 'Empirical Evaluation of Approximation Algorithms for Generalized Graph Coloring and Uniform Quasi-wideness', 2019, 5, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (212, 'Subexponential-Time Algorithms for Maximum Independent Set in P_t-Free and Broom-Free Graphs', 2019, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (213, 'A Deterministic Polynomial Kernel for Odd Cycle Transversal and Vertex Multiway Cut in Planar Graphs', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (214, 'Efficient Approximation Schemes for Uniform-Cost Clustering Problems in Planar Graphs', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (215, 'Packing Directed Circuits Quarter-Integrally', 2019, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (216, 'A Polynomial-Time Approximation Scheme for Facility Location on Planar Graphs', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (217, 'Polynomial bounds for centered colorings on proper minor-closed graph classes', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (218, 'Subexponential-Time Algorithms for Finding Large Induced Sparse Subgraphs', 2019, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (219, 'Integer Programming and Incidence Treedepth', 2019, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (220, 'Reachability for Bounded Branching VASS', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (221, 'On width measures and topological problems on semi-complete digraphs', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (222, 'On Geometric Set Cover for Orthants', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (223, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (224, 'A note on the complexity of a phaseless polynomial interpolation', 2019, 2, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (225, 'Efficient Representation and Counting of Antipower Factors in Words', 2019, 6, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (226, 'Quasi-Linear-Time Algorithm for Longest Common Circular Factor', 2019, 9, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (227, 'Circular Pattern Matching with k Mismatches', 2019, 8, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (228, 'Weighted Shortest Common Supersequence Problem Revisited', 2019, 8, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (229, 'On-line weighted pattern matching', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (230, 'Longest Common Substring with Approximately k Mismatches', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (231, 'Quasi-Periodicity in Streams', 2019, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (232, 'Pattern Matching and Consensus Problems on Weighted Sequences and Profiles', 2019, 3, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (233, 'Longest Common Substring Made Fully Dynamic', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (234, 'Internal Dictionary Matching', 2019, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (235, 'Syntactic View of Sigma-Tau Generation of Permutations', 2019, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (236, 'Optimizing Egalitarian Performance when Colocating Tasks with Types for Cloud Data Center Resource Management', 2019, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (237, '(1 + epsilon)-Approximate Incremental Matching in Constant Deterministic Amortized Time', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (238, 'Fair Knapsack', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (239, 'A Quantitative Analysis of Multi-Winner Rules', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (240, 'Approval-Based Elections and Distortion of Voting Rules', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (241, 'Committee Scoring Rules: Axiomatic Characterization and Hierarchy', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (242, 'Axiomatic characterization of committee scoring rules', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (243, 'Proportional Representation in Elections: STV vs PAV', 2019, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (244, 'Matchings under Preferences: Strength of Stability and Trade-Offs', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (245, 'How Similar Are Two Elections?', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (246, 'Uniformisation Gives the Full Strength of Regular Languages', 2019, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (247, 'The logical strength of BĂĽchi''s decidability theorem', 2019, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (248, 'Multivariate Ovulation Window Detection at OvuFriend', 2019, 10, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (249, 'On Boolean Representation of Continuous Data Biclustering', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (250, 'On resilient feature selection: Computational foundations of r-C-reducts', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (251, 'Paraconsistent Reasoning in Cops and Robber Game with Uncertain Information: A Simulation-Based Analysis', 2019, 3, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (252, 'Decision-Making Support Using Nonmonotonic Probabilistic Reasoning', 2019, 1, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (253, 'Learning signaling networks from combinatorial perturbations by exploiting siRNA off-target effects', 2019, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (254, 'ARA: accurate, reliable and active histopathological image classification framework with Bayesian deep learning', 2019, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (255, 'QChromosomeVisualizer: A new tool for 3D visualization of long simulations of polymer-like chromosome models', 2019, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (256, 'Random Walk Decay Centrality', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (257, 'Approximating APSP without Scaling: Equivalence of Approximate Min-plus and Exact Min-Max', 2019, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (258, 'BPscore: an effective metric for meaningful comparisons of structural chromosome segmentations', 2019, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (259, 'Clifford Algebras Meet Tree Decompositions', 2019, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (260, 'Losing Treewidth by Separating Subsets', 2019, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (261, 'Constant-Factor FPT Approximation for Capacitated k-Median', 2019, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (262, 'Lessons from Communication Problems that Nearly Jeopardized Development of Hardware-Software Support for a 1000-Device IoT Testbed', 2020, 15, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (263, 'ImaGINator: Conditional Spatio-Temporal GAN for Video Generation', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (264, 'G3AN: Disentangling motion and appearance for video generation', 2020, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (265, 'Extensions of Ď‰-Regular Languages', 2020, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (266, 'First-order tree-to-tree functions', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (267, 'Single-Use Automata and Transducers for Infinite Alphabets', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (268, 'Some Remarks on Deciding Equivalence for Graph-To-Graph Transducers', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (269, 'Undecidability of a weak version of MSO+U', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (270, 'From Gap-Exponential Time Hypothesis to Fixed Parameter Tractable Inapproximability: Clique, Dominating Set, and More', 2020, 7, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (271, 'Lower Bounds for the Parameterized Complexity of Minimum Fill-in and Other Completion Problems', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (272, 'An Approach to Regular Separability in Vector Addition Systems', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (273, 'Reachability in Fixed Dimension Vector Addition Systems with States', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (274, 'Universality Problem for Unambiguous VASS', 2020, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (275, 'Getting insight into the pan-genome structure with PangTree', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (276, 'Dimensionality Reduction for k-Distance Applied to Persistent Homology', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (277, 'A game of hide and seek in networks', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (278, 'The strategy of conquest', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (279, 'A PTAS for Euclidean TSP with Hyperplane Neighborhoods', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (280, 'Drawing graphs on few lines and few planes', 2020, 6, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (281, 'Low Entropy Sub-Networks Prevent the Integration of Metabolomic and Transcriptomic Data', 2020, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (282, 'Masserstein: Linear regression of mass spectra by optimal transport', 2020, 7, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (283, 'Knot_pullâ€”python package for biopolymer smoothing and knot detection', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (284, 'Breakpoint mapping of symptomatic balanced translocations links the EPHA6, KLF13 and UBR3 genes to novel disease phenotype', 2020, 20, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (285, 'New Hybrid Quantum Annealing Algorithms for Solving Vehicle Routing Problem', 2020, 9, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (286, 'Exact median-tree inference for unrooted reconciliation costs', 2020, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (287, 'Minimizing genomic duplication episodes', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (288, 'Parametrized Universality Problems for One-Counter Nets', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (289, 'Human Nature: The Subject and the Headache of IoT-Based Sociometric Studies', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (290, 'On Positive-Correlation-Promoting Reducts', 2020, 4, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (291, 'Single-Source Shortest Paths and Strong Connectivity in Dynamic Planar Graphs', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (292, 'Bisimulational categoricity', 2020, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (293, 'Many Visits TSP Revisited', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (294, 'The Asymmetric Travelling Salesman Problem In Sparse Digraphs', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (295, 'The PACE 2020 Parameterized Algorithms and Computational Experiments Challenge: Treedepth', 2020, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (296, 'A simple approach to nondecreasing paths', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (297, 'A High-Throughput Screen for Transcription Activation Domains Reveals Their Sequence Features and Permits Prediction by Deep Learning', 2020, 9, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (298, 'WQO dichotomy for 3-graph', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (299, 'Petri netâ€“based model of the human DNA base excision repair pathway', 2020, 5, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (300, 'Fair division in the presence of externalities', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (301, 'Deep Learning Versus Traditional Solutions for Group Trajectory Outliers', 2020, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (302, 'Hiding in Multilayer Networks', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (303, 'Partition decision trees: representation for efficient computation of the Shapley value extended to games with externalities', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (304, 'Signed Graph Games: Coalitional Games with Friends, Enemies and Allies', 2020, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (305, 'The Manipulability of Centrality Measures-An Axiomatic Approach', 2020, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (306, 'Improved approximation for Fractionally Subadditive Network Design', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (307, 'On Finite Entailment of Non-Local Queries in Description Logics', 2020, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (308, 'Ontology Focusing: Knowledge-Enriched Databases on Demand', 2020, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (309, 'Bisimulation and bisimilarity for fuzzy description logics under the GĂ¶del semantics', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (310, 'ExpTime Tableaux with Global Caching for Hybrid PDL', 2020, 1, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (311, 'GLN: a method to reveal unique properties of lasso type topology in proteins', 2020, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (312, 'Topoly: Python package to analyze topology of polymers', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (313, 'Computing Measures of Weak-MSO Definable Sets of Trees', 2020, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (314, 'A Quasi-Polynomial Black-Box Algorithm for Fixed Point Evaluation', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (315, 'A Type System Describing Unboundedness', 2020, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (316, 'Bisimulation Finiteness of Pushdown Systems Is Elementary', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (317, 'Cost Automata, Safe Schemes, and Downward Closures', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (318, 'Higher-Order Nonemptiness Step by Step', 2020, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (319, 'On the Expressive Power of Higher-Order Pushdown Systems', 2020, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (320, 'Parity Games: Another View on Lehtinen''s Algorithm', 2020, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (321, 'Recursion Schemes, the MSO Logic, and the U quantifier', 2020, 1, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (322, 'A Double Exponential Lower Bound for the Distinct Vectors Problem', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (323, 'The Complexity of Connectivity Problems in Forbidden-Transition Graphs And Edge-Colored Graphs', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (324, 'An Improved FPT Algorithm for Independent Feedback Vertex Set', 2020, 2, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (325, 'On the Maximum Weight Independent Set Problem in Graphs without Induced Cycles of Length at Least Five', 2020, 4, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (326, 'Quasi-polynomial time approximation schemes for the Maximum Weight Independent Set Problem in H-free graphs', 2020, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (327, 'Two lower bounds for p-centered colorings', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (328, 'Hamiltonian Cycle Parameterized by Treedepth in Single Exponential Time and Polynomial Space', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (329, 'Shorter Labeling Schemes for Planar Graphs', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (330, 'VC Density of Set Systems Definable in Tree-Like Graphs', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (331, 'An exponential time parameterized algorithm for planar disjoint paths', 2020, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (332, 'Clustering Powers of Sparse Graphs', 2020, 4, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (333, 'Enumerating Minimal Dominating Sets in Kt-free Graphs and Variants', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (334, 'Finding Large H-Colorable Subgraphs in Hereditary Graph Classes', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (335, 'First-Order Interpretations of Bounded Expansion Classes', 2020, 7, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (336, 'Model-Checking on Ordered Structures', 2020, 9, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (337, 'On Polynomial Recursive Sequences', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (338, 'On low rank-width colorings', 2020, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (339, 'Quasi-Polynomial Time Approximation Schemes for Packing and Covering Problems in Planar Graphs', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (340, 'Tight Complexity Lower Bounds for Integer Linear Programming with Few Constraints', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (341, 'A Linear-Time Algorithm for Seeds Computation', 2020, 5, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (342, 'Approximating Longest Common Substring with k mismatches: Theory and Practice', 2020, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (343, 'Counting Distinct Patterns in Internal Dictionary Matching', 2020, 8, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (344, 'Dynamic and Internal Longest Common Substring', 2020, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (345, 'Efficient Computation of 2-Covers of a String', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (346, 'Efficient Enumeration of Distinct Factors Using Package Representations', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (347, 'Faster algorithms for 1-mappability of a sequence', 2020, 6, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (348, 'Indexing weighted sequences: Neat and efficient', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (349, 'Internal Quasiperiod Queries', 2020, 7, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (350, 'Shortest Covers of All Cyclic Shifts of a String', 2020, 7, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (351, 'Streaming k-mismatch with error correcting and applications', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (352, 'String periods in the order-preserving model', 2020, 6, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (353, 'The Number of Repetitions in 2D-Strings', 2020, 6, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (354, 'Unary Words Have the Smallest Levenshtein k-Neighbourhoods', 2020, 5, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (355, 'Universal reconstruction of a string', 2020, 5, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (356, 'k-Approximate Quasiperiodicity under Hamming and Edit Distance', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (357, 'Autopilot: workload autoscaling at Google', 2020, 11, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (358, 'Scheduling Methods to Reduce Response Latency of Function as a Service', 2020, 2, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (359, 'Derived Hall algebras of one-cycle gentle algebras: The infinite global dimension case', 2020, 2, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (360, 'Complexity of Computing the Shapley Value in Games with Externalities', 2020, 1, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (361, 'Comparing election methods where each voter ranks only few candidates', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (362, 'A characterization of the single-peaked single-crossing domain', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (363, 'Drawing a map of elections in the space of statistical cultures', 2020, 5, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (364, 'Evaluating committees for representative democracies: The distortion and beyond', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (365, 'Mixed integer programming with convex/concave constraints: Fixed-parameter tractability and applications to multicovering and voting', 2020, 5, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (366, 'Price of fairness in budget division and probabilistic social choice', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (367, 'Proportionality and the Limits of Welfarism', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (368, 'Utilitarian welfare and representation guarantees of approval-based multiwinner rules', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (369, 'On the Succinctness of Alternating Parity Good-For-Games Automata', 2020, 4, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (370, 'Regular Choice Functions and Uniformisations For countable Domains', 2020, 2, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (371, 'Uniformisations of Regular Relations Over Bi-Infinite Words', 2020, 3, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (372, 'Research on Heuristic Optimization and Operations in IoT', 2020, 4, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (373, 'Approximate Decision Tree Induction over Approximately Engineered Data Features', 2020, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (374, 'From Big Data to business analytics: The case study of churn prediction', 2020, 4, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (375, 'Heuristic Search of Exact Biclusters in Binary Data', 2020, 3, 100);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (376, 'Rough-set-driven approach for attribute reduction in fuzzy formal concept analysis', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (377, 'The Problem of Finding the Simplest Classifier Ensemble is NP-Hard â€“ A Rough-Set-Inspired Formulation Based onÂ Decision Bireducts', 2020, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (378, 'IsoSpec2: Ultrafast Fine Structure Calculator', 2020, 3, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (379, 'Algorithmic Discovery of Tactical Combinations for Advanced Organic Syntheses', 2020, 7, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (380, 'A Paraconsistent ASP-like Language with Tractable Model Generation', 2020, 1, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (381, 'On the Probability and Cost of Ignorance, Inconsistency, Nonsense and More', 2020, 1, 40);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (382, 'Rough Forgetting', 2020, 2, 20);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (383, 'A mathematical model of the metastatic bottleneck predicts patient outcome and response to cancer treatment', 2020, 4, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (384, 'Eleven grand challenges in single-cell data science', 2020, 52, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (385, 'Feature selection strategies for drug sensitivity prediction', 2020, 8, 140);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (386, 'The Unconstrained Diameters of the Duplication-Loss Cost and the Loss Cost', 2020, 3, 70);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (387, 'Aggregate Queries on Sparse Databases', 2020, 1, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (388, 'Register Automata with Extrema Constraints, and an Application to Two-Variable Logic', 2020, 2, 200);
INSERT INTO publikacje (id, tytul, rok, autorzy, punkty) VALUES (389, 'Automated inference of gene regulatory networks using explicit regulatory modules', 2020, 2, 70);

SELECT tytul FROM publikacje
WHERE rok = 2020 AND autorzy > 0 AND (punkty / autorzy) >= 100
ORDER BY autorzy;


