# Generated by Django 5.2 on 2025-05-19 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roads", "0002_route_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="background",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to="roads.backgroundimage",
            ),
        ),
    ]
