# Generated by Django 5.2 on 2025-05-19 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("roads", "0004_gameboard_dot"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gameboard",
            old_name="title",
            new_name="name",
        ),
    ]
