# Generated by Django 5.2 on 2025-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roads", "0006_gamepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamepath",
            name="data",
            field=models.JSONField(
                default={},
                help_text="Obiekt: { 'hsl(0,100%,50%)': [ {'row':1,'col':2}, ... ], ... }",
            ),
            preserve_default=False,
        ),
    ]
